/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/
package com.s2474.classicmodels.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.s2474.classicmodels.Orderdetails;
import com.s2474.classicmodels.Orders;


/**
 * ServiceImpl object for domain model class Orders.
 *
 * @see Orders
 */
@Service("classicmodels.OrdersService")
public class OrdersServiceImpl implements OrdersService {

    private static final Logger LOGGER = LoggerFactory.getLogger(OrdersServiceImpl.class);

    @Autowired
	@Qualifier("classicmodels.OrderdetailsService")
	private OrderdetailsService orderdetailsService;

    @Autowired
    @Qualifier("classicmodels.OrdersDao")
    private WMGenericDao<Orders, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Orders, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "classicmodelsTransactionManager")
    @Override
	public Orders create(Orders orders) {
        LOGGER.debug("Creating a new Orders with information: {}", orders);
        Orders ordersCreated = this.wmGenericDao.create(orders);
        if(ordersCreated.getOrderdetailses() != null) {
            for(Orderdetails orderdetailse : ordersCreated.getOrderdetailses()) {
                orderdetailse.setOrders(ordersCreated);
                LOGGER.debug("Creating a new child Orderdetails with information: {}", orderdetailse);
                orderdetailsService.create(orderdetailse);
            }
        }
        return ordersCreated;
    }

	@Transactional(readOnly = true, value = "classicmodelsTransactionManager")
	@Override
	public Orders getById(Integer ordersId) throws EntityNotFoundException {
        LOGGER.debug("Finding Orders by id: {}", ordersId);
        Orders orders = this.wmGenericDao.findById(ordersId);
        if (orders == null){
            LOGGER.debug("No Orders found with id: {}", ordersId);
            throw new EntityNotFoundException(String.valueOf(ordersId));
        }
        return orders;
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
	@Override
	public Orders findById(Integer ordersId) {
        LOGGER.debug("Finding Orders by id: {}", ordersId);
        return this.wmGenericDao.findById(ordersId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "classicmodelsTransactionManager")
	@Override
	public Orders update(Orders orders) throws EntityNotFoundException {
        LOGGER.debug("Updating Orders with information: {}", orders);
        this.wmGenericDao.update(orders);

        Integer ordersId = orders.getOrderNumber();

        return this.wmGenericDao.findById(ordersId);
    }

    @Transactional(value = "classicmodelsTransactionManager")
	@Override
	public Orders delete(Integer ordersId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Orders with id: {}", ordersId);
        Orders deleted = this.wmGenericDao.findById(ordersId);
        if (deleted == null) {
            LOGGER.debug("No Orders found with id: {}", ordersId);
            throw new EntityNotFoundException(String.valueOf(ordersId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "classicmodelsTransactionManager")
	@Override
	public Page<Orders> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Orders");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Page<Orders> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Orders");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service classicmodels for table Orders to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "classicmodelsTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "classicmodelsTransactionManager")
    @Override
    public Page<Orderdetails> findAssociatedOrderdetailses(Integer orderNumber, Pageable pageable) {
        LOGGER.debug("Fetching all associated orderdetailses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("orders.orderNumber = '" + orderNumber + "'");

        return orderdetailsService.findAll(queryBuilder.toString(), pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service OrderdetailsService instance
	 */
	protected void setOrderdetailsService(OrderdetailsService service) {
        this.orderdetailsService = service;
    }

}

